config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create, :update, :destroy]
      
    end
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  deadline   :date
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
class Task < ApplicationRecord
    has_one_attached :eyecatch

    validates :title, presence: true
    validates :content, presence: true

    has_many :comments, dependent: :destroy
    belongs_to :user
    belongs_to :board

    def comment_count
        comments.count
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: [:show, :edit, :update]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    def index
        @board = Board.find(params[:board_id])
        @tasks = @board.tasks.all
    end

    def show
        @comments = @task.comments
    end

    def new
        board = Board.find(params[:board_id])
        @task = board.tasks.build
    end

    def create
        @board = current_user.boards.find(params[:board_id])
        @task = @board.tasks.build(task_params.merge!(user_id: current_user.id))
        if @task.save
            redirect_to board_tasks_path(@board), notice: '保存完了'
        else
            flash.now[:error] = '保存失敗'
            render :new
        end
    end

    def edit
    end

    def update
        @board = Board.find(params[:board_id])
        @task = @board.tasks.find(params[:id])
        if @task.update(task_params)
            redirect_to board_task_path(@board, @task), notice: '更新出来ました'
        else
            flash.now[:error] = '更新出来ませんでした'
            render :edit
        end
    end

    def destroy
        board = Board.find(params[:board_id])
        task = board.tasks.find(params[:id])
        task.destroy!
        redirect_to board_tasks_path(board), notice: '削除に成功しました'
    end

    private
    def task_params
        params.require(:task).permit(:title, :content, :eyecatch)
    end

    def set_task
        @board = Board.find(params[:board_id])
        @task = @board.tasks.find(params[:id])
    end
end

app/views/tasks/_form.html.haml
.form_container
  .new_label New Card
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @task, local: true) do |f|
    %div
      = f.label :eyecatch, 'EyeCatch'
    %div
      = f.file_field :eyecatch
    .title_label
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    .content_label
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/edit.html.haml
.form_container
  .new_label New Card
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message
  = form_with(model: [@board, @task], local: true) do |f|
    %div
      = f.label :eyecatch, 'EyeCatch'
    %div
      = f.file_field :eyecatch
    .title_label
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    .content_label
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/index.html.haml
.container
  .top_label
    Brackets
  - @tasks.each do |task|
    .card
      - if task.eyecatch.attached?
        .card_image
          = image_tag task.eyecatch
      - if user_signed_in? && current_user.has_task_written?(task)
        .board_detail_actions
          .dropdown
            = image_tag 'Combined Shape.svg', class: 'dropbtn'
            .dropdown-content.mini
              = link_to 'Edit', edit_board_task_path(board_id: @board.id, id: task.id)
              = link_to 'Delete', board_task_path(board_id: @board.id, id: task.id), data: { method: 'delete' , confirm: 'Are you sure you want to delete it?' }
      .card_content
        = link_to board_task_path(board_id: @board.id, id: task.id) do
          .card_title
            = task.title
          .card_text
            = task.content
        .card_comments_count
          %span= task.comment_count
          = image_tag 'Shape.png' 
  = link_to new_board_task_path do
    .add_new
      .add_new_label + Add new task

app/views/tasks/new.html.haml
.form_container
  .new_label New Card
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @task, url: board_tasks_path(@task.board), local: true) do |f|
    %div
      = f.label :eyecatch, 'EyeCatch'
    %div
      = f.file_field :eyecatch
    .title_label
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    .content_label
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/show.html.haml
.task_container
  %h1.task_title= @task.title
  .task_detail_actions
    .dropdown
      = image_tag 'Combined Shape.svg', class: 'dropbtn'
      .dropdown-content.mini
        = link_to 'Edit', edit_board_task_path(board_id: @task.board_id, id: @task.id)
        = link_to 'Delete',board_task_path(board_id: @task.board_id, id: @task.id), data: { method: 'delete' , confirm: 'Are you sure you want to delete it?' }
  .task
    - if @task.eyecatch.attached?
      .task_image
        = image_tag @task.eyecatch
    .task_content
      = @task.content

.task_comment.index
  .comment_label Comment
  .task_comment_set
    = image_tag 'default-avatar.png', class: 'header_avatar'
    - @comments.each do |comment|
      .task_comment
        %p= comment.content

= link_to new_board_task_comment_path(board_id: @task.board_id, task_id: @task.id) do
  .btn-secondary
    + Add new comment