config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create, :update, :destroy]
      
    end
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true

    has_many :tasks, dependent: :destroy
    has_many :comments, dependent: :destroy
    belongs_to :user
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    before_action :set_board, only: [:show]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

    def index
        @boards = Board.all
    end

    def show
    end

    def new
        @board = current_user.boards.build
    end

    def create
        @board = current_user.boards.build(board_params)
        if @board.save
            redirect_to boards_path(@board), notice: '保存完了'
        else
            flash.now[:error] = '保存失敗'
            render :new
        end
    end

    def edit
        @board = current_user.boards.find(params[:id])
    end

    def update
        @board = current_user.boards.find(params[:id])
        if @board.update(board_params)
            redirect_to boards_path(@board), notice: '更新出来ました'
        else
            flash.now[:error] = '更新出来ませんでした'
            render :edit
        end
    end

    def destroy
        board = current_user.boards.find(params[:id])
        board.destroy!
        redirect_to root_path, notice: '削除に成功しました'
    end

    private
    def board_params
        params.require(:board).permit(:title, :content)
    end

    def set_board
        @board = Board.find(params[:id])
    end
end

app/views/boards/_form.html.haml
.form_container
  .new_label New Board
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @board, local: true) do |f|
    .title_label
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    .content_label
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    = f.submit 'Submit', class: 'btn-primary'

app/views/boards/edit.html.haml
= render 'form', board: @board

app/views/boards/index.html.haml
.container
  .top_label
    All Boards
  - @boards.each do |board|
    .card
      - if user_signed_in? && current_user.has_written?(board)
        .board_detail_actions
          .dropdown
            = image_tag 'Combined Shape.svg', class: 'dropbtn'
            .dropdown-content.mini
              = link_to 'Edit', edit_board_path(board)
              = link_to 'Delete', board_path(board), data: { method: 'delete' , confirm: 'Are you sure you want to delete it?' }
      .card_content
        = link_to board_tasks_path(board) do
          .card_title
            = board.title
        .card_text
          = board.content
        .card_detail
          = image_tag board.user.avatar_image
  = link_to new_board_path(@boards) do
    .add_new
      .add_new_label + Add new board

app/views/boards/new.html.haml
= render 'form', board: @board